-- ============================================
-- QUANTUM NEXUS LNK - Master Database README
-- 資料庫總覽與執行指南
-- ============================================
-- 
-- 最後更新 Last Updated: 2025-12-23
-- 
-- ============================================
-- 目錄結構 DIRECTORY STRUCTURE
-- ============================================
--
-- supabase/
-- ├── README.sql                    -- 本檔案：總覽與執行指南
-- │
-- ├── 01_drop/                      -- 步驟 1: 刪除舊表格
-- │   ├── 01_main.sql              -- 刪除主網站表格
-- │   ├── 02_comments.sql          -- 刪除留言系統表格
-- │   ├── 03_reports.sql           -- 刪除報告系統表格
-- │   ├── 04_gallery.sql           -- 刪除畫廊表格
-- │   ├── 05_reactions.sql         -- 刪除反應系統表格
-- │   ├── 06_feature_settings.sql  -- 刪除功能開關設定
-- │   ├── 07_shop.sql              -- 刪除電商表格
-- │   ├── 09_landing_sections.sql  -- 刪除首頁區塊表格
-- │   └── 10_theme.sql             -- 刪除主題配置表格
-- │
-- ├── 02_add/                       -- 步驟 2: 建立新表格
-- │   ├── 01_main.sql              -- 主網站表格（含 site_admins + JWT trigger）
-- │   ├── 02_comments.sql          -- 留言系統表格
-- │   ├── 03_reports.sql           -- 報告系統表格
-- │   ├── 04_gallery.sql           -- 畫廊表格
-- │   ├── 05_reactions.sql         -- 反應系統表格
-- │   ├── 06_cross_triggers.sql    -- 跨表觸發器
-- │   ├── 06_feature_settings.sql  -- 功能開關設定
-- │   ├── 07_shop.sql              -- 電商核心表格
-- │   ├── 08_shop_functions.sql    -- 電商函數
-- │   ├── 09_landing_sections.sql  -- 首頁區塊表格
-- │   └── 10_theme.sql             -- 主題配置表格（Singleton）
-- │
-- └── 03_seed/                      -- 步驟 3: 插入預設資料
--     ├── 01_main.sql              -- 主網站預設資料
--     ├── 02_comments.sql          -- 留言系統預設資料
--     ├── 03_shop.sql              -- 電商預設資料
--     ├── 04_features_landing.sql  -- 功能開關與 Landing 預設資料
--     ├── 05_gallery.sql           -- 畫廊預設資料
--     ├── 06_blog.sql              -- 部落格預設資料
--     └── 07_theme.sql             -- 主題配置預設資料
--
-- ============================================
-- 合併檔案 COMBINED FILES
-- ============================================
--
-- 為方便一次性執行，已預先合併所有 SQL 檔案：
--
-- - COMBINED_ADD.sql   (~79KB) - 建立所有表格/函數/RLS
-- - COMBINED_DROP.sql  (~8KB)  - 刪除所有表格（重建用）
-- - COMBINED_SEED.sql  (~13KB) - 插入預設資料
--
-- 【全新安裝】只需執行：
--    ① COMBINED_ADD.sql
--    ② COMBINED_SEED.sql
--
-- 【重建資料庫】執行順序：
--    ① COMBINED_DROP.sql
--    ② COMBINED_ADD.sql
--    ③ COMBINED_SEED.sql
--
-- ============================================
--  全新安裝 FRESH INSTALL（空資料庫）
-- ============================================
--
-- 請在 Supabase Dashboard > SQL Editor 中，按以下順序執行：
--
-- 【步驟 1 - DROP】跳過（空資料庫不需要）
--
-- 【步驟 2 - ADD】建立新表格（按順序）
--    ① 02_add/01_main.sql
--    ② 02_add/02_comments.sql
--    ③ 02_add/03_reports.sql
--    ④ 02_add/04_gallery.sql
--    ⑤ 02_add/05_reactions.sql
--    ⑥ 02_add/06_cross_triggers.sql
--    ⑦ 02_add/06_feature_settings.sql
--    ⑧ 02_add/07_shop.sql
--    ⑨ 02_add/08_shop_functions.sql
--    ⑩ 02_add/09_landing_sections.sql
--    ⑪ 02_add/10_theme.sql
--
-- 【步驟 3 - SEED】插入預設資料（按順序）
--    ① 03_seed/01_main.sql
--    ② 03_seed/02_comments.sql
--    ③ 03_seed/03_shop.sql
--    ④ 03_seed/04_features_landing.sql
--    ⑤ 03_seed/05_gallery.sql
--    ⑥ 03_seed/06_blog.sql
--    ⑦ 03_seed/07_theme.sql
--
-- 【步驟 4 - 新增第一位 Admin】
--    執行以下 SQL（替換 email）：
--
--    INSERT INTO public.site_admins (email, role)
--    VALUES ('your-email@example.com', 'owner');
--
-- ⚠️ 完成後請重新登入網站，角色才會生效！
--
-- ============================================
-- 🔄 重建資料庫 REBUILD DATABASE（已有資料）
-- ============================================
--
-- ⚠️ 警告：此操作會刪除所有資料！
--
-- 【步驟 1 - DROP】刪除舊表格（反向順序）
--    ① 01_drop/10_theme.sql
--    ② 01_drop/09_landing_sections.sql
--    ③ 01_drop/07_shop.sql
--    ④ 01_drop/06_feature_settings.sql
--    ⑤ 01_drop/05_reactions.sql
--    ⑥ 01_drop/04_gallery.sql
--    ⑦ 01_drop/03_reports.sql
--    ⑧ 01_drop/02_comments.sql
--    ⑨ 01_drop/01_main.sql
--
-- 【步驟 2, 3】同上「全新安裝」
--

-- ============================================
-- 依賴關係 DEPENDENCIES
-- ============================================
--
-- 1. comments 依賴 main (需要 posts 表)
-- 2. reports 依賴 comments (需要 site_admins 表)
-- 3. gallery 依賴 comments (需要 site_admins 表)
-- 4. reactions 依賴 gallery, comments
-- 5. cross_triggers 依賴 posts, gallery_items, comments, reactions
-- 6. feature_settings 獨立（但 shop 的 is_shop_visible() 會讀取它）
-- 7. shop 依賴 main + feature_settings (需要 auth.users + feature_settings)
-- 8. shop_functions 依賴 shop + extensions (pg_cron, vault)
-- 9. landing_sections 依賴 gallery (gallery_categories 外鍵)
-- 10. theme 獨立 (Singleton 表，無依賴)
--
-- ⚠️ 請務必按照編號順序執行！
--
-- ============================================
-- RBAC 角色說明 RBAC ROLES
-- ============================================
--
-- site_admins 表支援兩種角色：
-- - owner: 最高權限，可管理金流設定與財務數據
-- - editor: 一般管理員，可管理商品/訂單/內容
--
-- 角色透過 JWT app_metadata.role 傳遞，無需每次查詢資料庫。
-- Trigger 會自動同步 site_admins 變更到 auth.users。
--
-- 新增 admin 範例：
-- INSERT INTO public.site_admins (email, role) 
-- VALUES ('you@example.com', 'owner');
--
-- ⚠️ 角色變更需要重新登入後才會生效！
--
-- ============================================
